### ISSUE TITLE
Can't remove a mod with ferium remove (mod name)

### ISSUE THREAD

**Issue by Sourpunch14** [gorilla-devs/ferium#246]
Attempting to use ferium remove isn't removing the mod and tells me there is no mod with that name however using ferium add tells me the mod is already there and can't be added.

## To Reproduce
I installed a Convenient mobGriefing using ferium add. Trying to remove it with ferium remove doesn't work.

## Software version
- Windows 11
- Ferium Version 4.2.2

## Additional information
https://modrinth.com/mod/convenient-mobgriefing 
mod link, using it's project ID does the same thing

**Comment by theRookieCoder** [comment]
Works fine for me. I think the problem is that you told ferium to delete two separate mods, one called `Convenient` and another mod called `mobGriefing`. If you want to remove `Convenient mobGriefing` you have to either 'escape' the space using a backslash, or just enclose the name in quotes, or else your shell will treat it as 2 seperate arguments

**Comment by Aquaeyes** [comment]
For me the issues presents only when selecting after just using Ferium Remove without providing an ID/Name. So the raw CLI stuff works, just not the selection interface.

**Comment by theRookieCoder** [comment]
Make sure you select the mod using the space bar, and then press enter. I can remove mods (including the one you linked) just finew it the ui too.
