### ISSUE TITLE
Implement filtering for GitHub releases.

### ISSUE THREAD

**Issue by dmoklyakov** [gorilla-devs/ferium#29]
Maybe it is not a best idea (because it breaks backward compatibility) but I propose to modify config structure for GitHub mods.
From this:

```
"GitHubRepository": [
    "someGithubUser",
    "someRepoName"
]
```

To this:
```
"GitHubRepository": {
    "author": "someGithubUser",
    "repo": "someRepoName",
    "file_mask": ".*-release.jar$" // This parameter is a regular expression.
}
```

**Comment by KyleUltimate** [comment]
This would also help downloading this mod in 1.18, since currently ferium downloads the 1.18 version
https://github.com/xCollateral/VulkanMod/releases

**Comment by jhmaster2000** [comment]
+1 to this, Ferium currently fails to correctly install [19MisterX98/SeedcrackerX](https://github.com/19MisterX98/SeedcrackerX/releases) because of the `*-api.jar` file provided, which I assume Ferium picks because its the top one on the list. Something like:
```sh
ferium add 19MisterX98/SeedcrackerX --excludefiles "*-api.jar"
```
would fix it nicely. (I don't see a way to filter out the right file with an inclusion glob pattern instead of an exclusion one)

**Comment by theRookieCoder** [comment]
Moved to #155

Let me know if the GitHub filters [I have 'designed'](https://github.com/gorilla-devs/ferium/issues/155#issuecomment-1481303888) are adequate.
