### ISSUE TITLE
Mod being removed cause html error

### ISSUE THREAD

**Issue by otter501** [gorilla-devs/ferium#296]
## Description
When I tried to update today, I had a html 404 Not Found error, This was caused by the mod author taking down a mod I used

## To Reproduce
Get a mod then have the mod author take the mod down

## Software version
- OS Arch Linux
- Ferium Version 4.4.0

**Comment by theRookieCoder** [comment]
I cannot magically bring back a mod from the dead if the author chose to take it down. I suggest downloading the latest version, putting it in your [`user` folder](https://github.com/gorilla-devs/ferium#external-mods), and removing the mod from your ferium profile.

**Comment by otter501** [comment]
i was thinking more of the error not completely stopping the update and it would instead ask if you want tk remove the mod from the mods list

**Comment by theRookieCoder** [comment]
Oh well there a few reasons to not do that. Firstly having incompatible mods in your profile is fine and normal, since it doesn't affect the upgrading process anyways. When updating to a new Minecraft version, some mods that haven't been updated (and might later) can be left in there so that you can just ferium upgrade again later.

**Comment by theRookieCoder** [comment]
Sorry I didn't really understand what you were saying in your initial comment.

I think some mods were temporarily taken down a few days ago. I feel like mods being taken down is niche enough that I don't want to bother with setting up such a feature.
