### ISSUE TITLE
Change the way internet connection availability is checked

### ISSUE THREAD

**Issue by theRookieCoder** [gorilla-devs/ferium#310]
The current crate I'm using doesn't work properly on some devices and networks.

The best way to check for a usable internet connection in this case is to just ping `api.modrinth.com`, `api.curseforge.com`, and `api.github.com`.

**Comment by T3sT3ro** [comment]
Is the `check_internet` even needed? Won't setting timeout for request be enough?

**Comment by theRookieCoder** [comment]
I was thinking it would look way better to alert the user before any tasks are started, in the end it's just personal preference and doesn't impact the code much.

**Comment by T3sT3ro** [comment]
Correct me if I'm wrong, but doesn't `check_internet` add an extra request and delay to each request? I see that it's awaited, so I was thinking that it 
1. First synchronously checks connectivity to servers adding ~200ms delay (give or take)
2. Only after connectivity has been established, it sends first content requests

I was thinking that it would be better to print an animated "Fetching data..." that starts in parallel with actual content requests and update the text with "Seems like connection is slow..." if no response comes after a while.

**Comment by theRookieCoder** [comment]
> check_internet add an extra request and delay to each request

Huh how so? It's only run once in the beginning of a subcommand if internet connectivity is required.

> Only after connectivity has been established, it sends first content requests

If I'm understanding this correctly, this is what happens now as well.

> update the text with "Seems like connection is slow..."

Again, the current check does show this message and checks _again_ before finally erroring out.

**Comment by T3sT3ro** [comment]
I wrote "request" but meant "each command that performs a `check_internet` blocks until there is a response, making sure that client has internet".

```mermaid
sequenceDiagram
  autonumber
  ferium->>+server: check(timeout=1)
  Note right of server: check_internet tries to create<br/>a TCP connection to clients3.google.com:80<br/>This adds initial delay to any command
  server->>-ferium: OK
  Note over ferium, server: supposedly internet is present
  ferium->>+server: actual requests to modrinth/curseforge/github
  server->>-ferium: responses
```

For example that's how `ferium upgrade` is implemented:

```rust
SubCommands::Upgrade => {
    check_internet().await?; 
    // ^ this can take for example 900ms just 
    //   to check if user has internet (or up to 4s)
    let profile = get_active_profile(&mut config)?;
    check_empty_profile(profile)?;
    subcommands::upgrade(modrinth, curseforge, github, profile).await?; 
    // ^ actual request to modrinth/CF/github starts here
    //   after ~900ms (or more if check_internet takes longer)
}
```

What I'm saying is that I think `check_internet` is not needed at all. You can start by printing "Fetching information from <platform>", immediately perform a network request to curseforge/modrinth/github and put timeout on that. If there is no connection, the request will fail on it's own and print appropriate information. Instead of "ferium requires internet to function" you would just do "Fetching information from Modrinth... Modrinth takes long to respong..."

check_internet` assumes, that If I can't connect to "clients3.google.com:80" or "detectportal.firefox.com:80", then I have no internet and can't connect to modrinth (which is false, but also unlikely that those domains would be down). I think it can also lead to ferium timing out for users with slow connections or roaming on unstable network.

In my opinion there should be no timeout (unless maybe specified in arguments?), just a function that observes if response came under 4 seconds, and if not it should print "It takes longer than usual...".

**Comment by T3sT3ro** [comment]
> Correct me if I'm wrong, but isn't that exactly what a timeout is meant to do?

From my understanding the timeout now terminates the process after 4 seconds if no response comes. What I had in mind was waiting indefinitely until a response comes, only notifying after 4 sec, and wait for termination sequence ^C to stop waiting.

**Comment by theRookieCoder** [comment]
> What I had in mind was waiting indefinitely until a response comes, only notifying after 4 sec, and wait for termination sequence ^C to stop waiting.

My main issue with something like this is that it can break scripting. Also, I think even the current method is overkill, I plan on just testing once and immediately erroring out if it fails.
