### ISSUE TITLE
Use ./ferium.json when exist

### ISSUE THREAD

**Issue by Jack-Works** [gorilla-devs/ferium#324]
### The Problem

I use ferium as a portable program, I hope the config can follow the program path.Ferium

### Your Solution(s)

Use ./ferium.json when exist

**Comment by theRookieCoder** [comment]
You can specify the config file path using the `FERIUM_CONFIG_FILE` environment variable. You can use something like [direnv](https://direnv.net) to set this path dynamically based on the directory you're in. I prefer having the user explicitly specify the file path rather than the program assume it is a specific file if it exists.
