### ISSUE TITLE
Cannot add mods from curseforge

### ISSUE THREAD

**Issue by greekVASILIS5** [gorilla-devs/ferium#346]
### Description

When trying to add any mod from curseforge i get this error: 

`Adding mod... ←[1;31mHTTP status client error (403 Forbidden) for url (https://api.curseforge.com/v1/mods/521783)←[0m
`

It does this to every curseforge mod i have tried. (i can download the mods from the site manually normally without any problems, without been signed in)
![Χωρίς τίτλο](https://github.com/gorilla-devs/ferium/assets/59560800/ea84f77a-3e25-40dd-8b22-6c1335ffd54f)

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by equinox** [comment]
Hi there, the reason for this is because recently there's been a discovery of malware being uploaded to curseforge, so as a precaution to limit ferium users' exposure to the malware, the developer took steps to make ferium not able to download mods from curseforge. Please take a look at this post [here](https://github.com/gorilla-devs/ferium/discussions/337#discussion-5272580) as to what ferium-specific steps were taken and how to regain access to curseforge mods through ferium ([the bottom most comment on that page](https://github.com/gorilla-devs/ferium/discussions/337#discussioncomment-6111930)).

I'd recommend also checking out this which explains the malware situation: [link here](https://github.com/fractureiser-investigation/fractureiser/blob/main/README.md).

**Comment by greekVASILIS5** [comment]
Ok i understand, but how do I set the api key that works;

**Comment by theRookieCoder** [comment]
I have no idea how to do this cleanly on Windows. I would suggest adding the environment variable in control panel.
