### ISSUE TITLE
Ferium cant download mods from curseforge

### ISSUE THREAD

**Issue by McBenjihood** [gorilla-devs/ferium#353]
### Description

When I try to add Mods from curseforge or trying to upgrade I get an error that reads like this:

Adding mod... HTTP status client error (403 Forbidden) for url (https://api.curseforge.com/v1/mods/397510)

I dont know if this a problem on my side or a ferium bug but it is very annoying. I reinstalled ferium but it still didnt work.

### Steps to reproduce

1. Run Ferium
2. Typ ferium upgrade or ferium add [any curseforge mod]

### Operating System

Windows

### Are you using the latest version of ferium?

- [x] I am using the latest version of ferium

**Comment by equinox** [comment]
Hi there, this functionality was removed because of the malware incident with popular mods containing malware, suspected to be coming from mods uploaded to curseforge. You can read more about ferium's developer's response [here](https://github.com/gorilla-devs/ferium/discussions/337).
This [here](https://github.com/fractureiser-investigation/fractureiser) is another worthwhile resource to check out you'd like to learn more about what the malware does and what mods were inpacted by this.

If you're okay with the response from curseforge and trust it, here's how you can get back access to curseforge mods:
`ferium --curseforge-api-key "$2a$10$sI.yRk4h4R49XYF94IIijOrO4i3W3dAFZ4ssOlNE10GYrDhc2j8K." upgrade` (should hopefully work since you're on Windows).
