### ISSUE TITLE
Fetch the subdirectory for mods that's Not Compatible

### ISSUE THREAD

**Issue by ChromaPIE** [gorilla-devs/ferium#386]
### The Problem

So as you can see in the issue that ive just posted https://github.com/gorilla-devs/ferium/issues/385, if a dependency mod adding to a project is actually "not compatible", or kept out for any other reasons, no further info other than the project ID will be shown.

So I gotta go googling "curseforge xxxxx", where the xxx is the ID, to finally find out what even is this dependency and whether it's truly incompatible or just because you need to ignore something. (and there's tooo much to type!! `--dont-check-mod-loader` pretty readable but not too finger-friendly. anyway it's just a casual complaint.)

### Your Solution(s)

If Ferium can go one step further by fetching the sub-directory, or, yeah, just show the entire URL for ppl to just click open it. it would be nice and neat to solve the problem.

**Comment by theRookieCoder** [comment]
> there's tooo much to type!! --dont-check-mod-loader pretty readable but not too finger-friendly

Fair enough, in hindsight it is far too long, and I should've added a short flag too.

In the future I'm planning on showing a menu when multiple mods or their dependencies can't be added, so that you can figure out which overrides to apply and not have to run the command again with the flags. (#175)
