### ISSUE TITLE
Ability to update modloader version

### ISSUE THREAD

**Issue by soup587** [gorilla-devs/ferium#403]
### The Problem

Not sure if there's a feature already for this and I just can't find it, but there doesn't seem to be a way of managing the specific version of an installed modloader for a profile.

This causes issues as it seems Ferium just uses the latest version at the time of making a profile, which will eventually lead to mods being incompatible as they update past the currently installed version.

**Comment by theRookieCoder** [comment]
Unfortunately it would be very difficult to support this since mods only specify the mod loader version in their manifests, which can only be read after the mod file is downloaded. Ferium relies on the information provided by mod authors on websites like modrinth and curseforge, and cannot download every file to check for compatibility.

As for unintended updates, #82 plans to add the ability to lock a mod to a specific version.

**Comment by soup587** [comment]
so i'm just   stuck unable to update mods because i'm stuck on an old forge version? unless i make a new instance???

**Comment by theRookieCoder** [comment]
Could you explain your exact situation here? I don't quite understand since I haven't used Forge in many years.

**Comment by theRookieCoder** [comment]
> I think this is relevant for Fabric as well. Would be nice if Ferium could just update the Fabric loader to latest when there's an update available. From what I understand, this should not cause compatibility issues with mods.

I think you misunderstood the title of this issue (I've edited it now to reflect what OP actually asked for). Anyways I believe updating the loader version is the responsibility of the launcher (or the user in case of the Mojang launcher). If #212 gets implemented it would make sense, but at the moment ferium deals with downloading mods and modpacks, not minecraft itself or mod loaders.
