### ISSUE TITLE
Unable to set custom path for config file via global flag

### ISSUE THREAD

**Issue by aBlueandaGreen** [gorilla-devs/ferium#406]
### Description

I’m quite inexperienced when it comes to the command line, so I apologize if I’m missing something incredibly simple. But I’ve been scratching my head at this for a while now.

### Steps to reproduce

1. Run `ferium --config-file "C:\Users\abcd\AppData\Roaming\.minecraft\.config\ferium\config.json"` (pretend `abcd` is my user directory).
2. Get the following: `error: 'ferium.exe' requires a subcommand but one was not provided`.

### Operating System

Windows

### Are you using the latest version of ferium?

- [x] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
`--config-file` is an _option_ rather than a command, meaning that it _modifies_ an existing command.
So what you need to do is add `--config-file "C:\Users\abcd\AppData\Roaming\.minecraft\.config\ferium\config.json"` to whatever command you want to run. This will only apply if you add the flag (i.e. it won't persist), so if you want to permanently reroute the config file you should use the `FERIUM_CONFIG_FILE` environment variable (use [Powertoys](https://powertoys.io/environment-variables-for-windows) to do this on Windows)
