### ISSUE TITLE
How to uninstall Ferium?

### ISSUE THREAD

**Issue by kevin930321** [gorilla-devs/ferium#413]
I can't find where ferium file is located

**Comment by theRookieCoder** [comment]
I assume you want to delete the executable? That entirely depends on how you installed ferium in the first place. If you didn't use a package manager, the easiest way would be to use `which ferium` to find the executable path and delete it using `rm`.

Also I'm just curious, are you uninstalling it because of some issues? If so I would love to know what it is.

**Comment by kevin930321** [comment]
I'm just want to know if i want to uninstall it some day, where can i find the file, i use cmd command to install it
