### ISSUE TITLE
No dependency check

### ISSUE THREAD

**Issue by ipegte93** [gorilla-devs/ferium#414]
### Description

I recently updated, but I'm having issues using it. It's not checking dependencies.
As far as I remember, before updating, it used to check the Required mods and ask whether to install Optional mods.

### Steps to reproduce

1. `ferium profile create`
2. Default mods directory
3. Minecraft version 1.20.4
4. Fabric
5. `ferium add sodium-extra`

### Operating System

macOS

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

### Additional Information

ferium installed from brew

**Comment by theRookieCoder** [comment]
The previous implementation had some issues, the biggest one is the dependencies were only dealt with when first adding the mod. They are supposed to be identified and added when upgrading mods. (#99) Another issues is that it did not implement recursive dependencies (the dependencies of dependencies (and so on) were not accounted for), implementing that would be easier when #99 is added.
I decided to temporarily remove the current implementation when refactoring the adding code. I wanted to implement the better solution rather than improve the existing flawed one. Unfortunately that means the feature is non-existent for the moment, but hopefully I'll be able to implement it asap.
