### ISSUE TITLE
Seems the feature of automately dependency resolve is missing? 

### ISSUE THREAD

**Issue by colinxu2020** [gorilla-devs/ferium#438]
### Description

When I try to use `ferium` to add a mod, I've suprisely found that the dependency of the mod was still missing(while the mod itself was added), when I had a look at the help of `add` subcommand, there wasn't `--dont-add-dependencies`  command(from #63).

I had a look at the changelog, but I can't found any clues about this, what had happened?

### Steps to reproduce

1. `ferium add connector`
2. `ferium upgrade`
3. The connector itself was in the correct place, but it's dependency was missing.

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
> I had a look at the changelog, but I can't found any clues about this, what had happened?

I failed to mention it in the changelog, but I removed the dependency feature because the previous implementation had some issues. One major issue is that it added the dependencies to the profile when the mod is added, and it does not consider dependencies tied with the specific version.

The solution for that would be to add dependencies during resolution-time, so when you're `upgrade`-ing (#99). Another issue was that dependencies were not resolved recursively, i.e. the dependencies of a dependency (and however farther the layers go) would not be resolved (#214). I wanted to have a proper implementation of dependency resolution rather than have a half-baked one.

**Comment by colinxu2020** [comment]
> > I had a look at the changelog, but I can't found any clues about this, what had happened?
> 
> I failed to mention it in the changelog, but I removed the dependency feature because the previous implementation had some issues. One major issue is that it added the dependencies to the profile when the mod is added, and it does not consider dependencies tied with the specific version.
> 
> The solution for that would be to add dependencies during resolution-time, so when you're `upgrade`-ing (#99). Another issue was that dependencies were not resolved recursively, i.e. the dependencies of a dependency (and however farther the chain goes) would not be resolved (#214). I wanted to have a proper implementation of dependency resolution rather than have a half-baked one.

Thinks for your quick response! I'm looking forward to the new dependency resolution system.
